const sampleListings = [
    {
        id: uuidv4(), question: "What is the speed of light?",
        subject: "Physics",
        topic: "Waves",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who is the author of '1984'?",
        subject: "Literature",
        topic: "Modern Classics",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the largest planet in our solar system?",
        subject: "Astronomy",
        topic: "Planets",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "What is the formula for the area of a circle?",
        subject: "Mathematics",
        topic: "Geometry",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who painted the Mona Lisa?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for gold?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the longest river in the world?",
        subject: "Geography",
        topic: "Rivers",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who developed the theory of relativity?",
        subject: "Physics",
        topic: "Modern Physics",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the main function of the kidneys?",
        subject: "Biology",
        topic: "Human Anatomy",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who is the Greek god of the sea?",
        subject: "Mythology",
        topic: "Greek Mythology",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the capital of Australia?",
        subject: "Geography",
        topic: "World Capitals",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed the 'Moonlight Sonata'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the smallest prime number?",
        subject: "Mathematics",
        topic: "Numbers",
        difficulty: "Easy",
        marks: 4,
    },
    {
        id: uuidv4(), question: "Who wrote 'To Kill a Mockingbird'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the formula for calculating work?",
        subject: "Physics",
        topic: "Work and Energy",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the process of plants making their food called?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "Who is the protagonist in 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which country is known as the Land of the Rising Sun?",
        subject: "Geography",
        topic: "Countries",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "What is the largest ocean on Earth?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who is credited with inventing the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Hard",
        marks: 10,
    },

    {
        id: uuidv4(), question: "What is the currency of Japan?",
        subject: "Economics",
        topic: "Currency",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who discovered penicillin?",
        subject: "Medicine",
        topic: "Medical Discoveries",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the largest desert in the world?",
        subject: "Geography",
        topic: "Deserts",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Starry Night'?",
        subject: "Art",
        topic: "Impressionism",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the process of converting water vapor to liquid called?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which planet is known as the 'Red Planet'?",
        subject: "Astronomy",
        topic: "Planets",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Iliad'?",
        subject: "Literature",
        topic: "Classics",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the largest mammal?",
        subject: "Biology",
        topic: "Animals",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who founded Microsoft?",
        subject: "Technology",
        topic: "Tech Companies",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for silver?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the study of earthquakes called?",
        subject: "Geology",
        topic: "Seismology",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who directed the movie 'Inception'?",
        subject: "Film",
        topic: "Directors",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Which gas do plants primarily use during photosynthesis?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed the 'Four Seasons'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the study of the universe called?",
        subject: "Astronomy",
        topic: "Cosmology",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the primary function of mitochondria?",
        subject: "Biology",
        topic: "Cell Biology",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Mona Lisa'?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the study of heredity called?",
        subject: "Biology",
        topic: "Genetics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who is known as the 'Father of Modern Physics'?",
        subject: "Physics",
        topic: "Scientists",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the boiling point of water in Celsius?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who invented the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the largest ocean in the world?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the formula for the area of a circle?",
        subject: "Mathematics",
        topic: "Geometry",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the powerhouse of the cell?",
        subject: "Biology",
        topic: "Cell Biology",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who wrote '1984'?",
        subject: "Literature",
        topic: "Modern Classics",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the largest planet in our solar system?",
        subject: "Astronomy",
        topic: "Planets",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the Mona Lisa?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for gold?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the longest river in the world?",
        subject: "Geography",
        topic: "Rivers",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who developed the theory of relativity?",
        subject: "Physics",
        topic: "Modern Physics",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the main function of the kidneys?",
        subject: "Biology",
        topic: "Human Anatomy",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who is the Greek god of the sea?",
        subject: "Mythology",
        topic: "Greek Mythology",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the capital of Australia?",
        subject: "Geography",
        topic: "World Capitals",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed the 'Moonlight Sonata'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the smallest prime number?",
        subject: "Mathematics",
        topic: "Numbers",
        difficulty: "Easy",
        marks: 4,
    },
    {
        id: uuidv4(), question: "Who wrote 'To Kill a Mockingbird'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the formula for calculating work?",
        subject: "Physics",
        topic: "Work and Energy",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the process of plants making their food called?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "Who is the protagonist in 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which country is known as the Land of the Rising Sun?",
        subject: "Geography",
        topic: "Countries",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "What is the largest ocean on Earth?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who is credited with inventing the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the currency of Japan?",
        subject: "Economics",
        topic: "Currency",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who discovered penicillin?",
        subject: "Medicine",
        topic: "Medical Discoveries",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the largest desert in the world?",
        subject: "Geography",
        topic: "Deserts",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Starry Night'?",
        subject: "Art",
        topic: "Impressionism",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the process of converting water vapor to liquid called?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which planet is known as the 'Red Planet'?",
        subject: "Astronomy",
        topic: "Planets",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Iliad'?",
        subject: "Literature",
        topic: "Classics",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the largest mammal?",
        subject: "Biology",
        topic: "Animals",
        difficulty: "Easy",
        marks: 6,
    },

    {
        id: uuidv4(), question: "Who founded Microsoft?",
        subject: "Technology",
        topic: "Tech Companies",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for silver?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the study of earthquakes called?",
        subject: "Geology",
        topic: "Seismology",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who directed the movie 'Inception'?",
        subject: "Film",
        topic: "Directors",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Which gas do plants primarily use during photosynthesis?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed the 'Four Seasons'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the study of the universe called?",
        subject: "Astronomy",
        topic: "Cosmology",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the primary function of mitochondria?",
        subject: "Biology",
        topic: "Cell Biology",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Mona Lisa'?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the study of heredity called?",
        subject: "Biology",
        topic: "Genetics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who is known as the 'Father of Modern Physics'?",
        subject: "Physics",
        topic: "Scientists",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the boiling point of water in Celsius?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who invented the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the largest ocean in the world?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Medium",
        marks: 8,
    },

    {
        id: uuidv4(), question: "What is the formula for calculating work?",
        subject: "Physics",
        topic: "Work and Energy",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the process of plants making their food called?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "Who is the protagonist in 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which country is known as the Land of the Rising Sun?",
        subject: "Geography",
        topic: "Countries",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "What is the largest ocean on Earth?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who is credited with inventing the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the currency of Japan?",
        subject: "Economics",
        topic: "Currency",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who discovered penicillin?",
        subject: "Medicine",
        topic: "Medical Discoveries",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the largest desert in the world?",
        subject: "Geography",
        topic: "Deserts",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Starry Night'?",
        subject: "Art",
        topic: "Impressionism",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the process of converting water vapor to liquid called?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Which planet is known as the 'Red Planet'?",
        subject: "Astronomy",
        topic: "Planets",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Iliad'?",
        subject: "Literature",
        topic: "Classics",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the largest mammal?",
        subject: "Biology",
        topic: "Animals",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who founded Microsoft?",
        subject: "Technology",
        topic: "Tech Companies",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for silver?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the study of earthquakes called?",
        subject: "Geology",
        topic: "Seismology",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who directed the movie 'Inception'?",
        subject: "Film",
        topic: "Directors",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Which gas do plants primarily use during photosynthesis?",
        subject: "Biology",
        topic: "Photosynthesis",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed the 'Four Seasons'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the study of the universe called?",
        subject: "Astronomy",
        topic: "Cosmology",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the primary function of mitochondria?",
        subject: "Biology",
        topic: "Cell Biology",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted the 'Mona Lisa'?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the study of heredity called?",
        subject: "Biology",
        topic: "Genetics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "Who is known as the 'Father of Modern Physics'?",
        subject: "Physics",
        topic: "Scientists",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "What is the boiling point of water in Celsius?",
        subject: "Science",
        topic: "States of Matter",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who invented the telephone?",
        subject: "History",
        topic: "Inventions",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the largest ocean in the world?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who wrote 'The Great Gatsby'?",
        subject: "Literature",
        topic: "American Classics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the formula for the area of a circle?",
        subject: "Mathematics",
        topic: "Geometry",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the powerhouse of the cell?",
        subject: "Biology",
        topic: "Cell Biology",
        difficulty: "Easy",
        marks: 6,
    },









    {
        id: uuidv4(), question: "What is the capital of Brazil?",
        subject: "Geography",
        topic: "World Capitals",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who wrote the play 'Hamlet'?",
        subject: "Literature",
        topic: "Shakespearean Plays",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for iron?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted 'The Persistence of Memory'?",
        subject: "Art",
        topic: "Surrealism",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the process of a caterpillar becoming a butterfly called?",
        subject: "Biology",
        topic: "Life Cycles",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who is the first female Prime Minister of the United Kingdom?",
        subject: "History",
        topic: "Political Leaders",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical formula for water?",
        subject: "Chemistry",
        topic: "Chemical Compounds",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed 'The Marriage of Figaro'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "What is the study of the Earth's atmosphere called?",
        subject: "Science",
        topic: "Atmospheric Science",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Who is the creator of the theory of evolution by natural selection?",
        subject: "Biology",
        topic: "Evolution",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the largest moon in the solar system?",
        subject: "Astronomy",
        topic: "Moons",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who is the author of 'The Catcher in the Rye'?",
        subject: "Literature",
        topic: "Modern Classics",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for potassium?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted 'The Scream'?",
        subject: "Art",
        topic: "Expressionism",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the process of a caterpillar becoming a butterfly called?",
        subject: "Biology",
        topic: "Life Cycles",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who was the first female Prime Minister of India?",
        subject: "History",
        topic: "Political Leaders",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical formula for ammonia?",
        subject: "Chemistry",
        topic: "Chemical Compounds",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed 'Swan Lake'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the study of weather called?",
        subject: "Meteorology",
        topic: "Weather Science",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Who proposed the theory of natural selection?",
        subject: "Biology",
        topic: "Evolution",
        difficulty: "Hard",
        marks: 9,
    },



    {
        id: uuidv4(), question: "What is the largest volcano in the solar system?",
        subject: "Astronomy",
        topic: "Volcanoes",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who wrote 'Moby-Dick'?",
        subject: "Literature",
        topic: "Classic Novels",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for sodium?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },
    // ... (17 more listings)
    {
        id: uuidv4(), question: "What is the chemical symbol for mercury?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who painted 'The Last Supper'?",
        subject: "Art",
        topic: "Renaissance Art",
        difficulty: "Hard",
        marks: 9,
    },
    {
        id: uuidv4(), question: "What is the process of a tadpole becoming a frog called?",
        subject: "Biology",
        topic: "Metamorphosis",
        difficulty: "Medium",
        marks: 7,
    },
    {
        id: uuidv4(), question: "Who was the first person to orbit the Earth?",
        subject: "Space Exploration",
        topic: "Astronauts",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the chemical formula for hydrogen peroxide?",
        subject: "Chemistry",
        topic: "Chemical Compounds",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who composed 'The Magic Flute'?",
        subject: "Music",
        topic: "Classical Music",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the study of the Earth's climate called?",
        subject: "Climatology",
        topic: "Climate Science",
        difficulty: "Hard",
        marks: 10,
    },




    {
        id: uuidv4(), question: "What is the highest mountain in the world?",
        subject: "Geography",
        topic: "Mountains",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the world's longest river?",
        subject: "Geography",
        topic: "Rivers",
        difficulty: "Easy",
        marks: 5,
    },

    {
        id: uuidv4(), question: "What is the name of the world's largest ocean?",
        subject: "Geography",
        topic: "Oceans",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "Who painted 'The Starry Night'?",
        subject: "Art",
        topic: "Post-Impressionism",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the speed of light?",
        subject: "Physics",
        topic: "Speed of Light",
        difficulty: "Hard",
        marks: 10,
    },
    {
        id: uuidv4(), question: "Who wrote 'War and Peace'?",
        subject: "Literature",
        topic: "Classic Novels",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the atomic number of helium?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },
    {
        id: uuidv4(), question: "Who invented the World Wide Web?",
        subject: "Computer Science",
        topic: "Inventions",
        difficulty: "Medium",
        marks: 8,
    },
    {
        id: uuidv4(), question: "What is the formula for water?",
        subject: "Chemistry",
        topic: "Chemical Compounds",
        difficulty: "Easy",
        marks: 5,
    },
    {
        id: uuidv4(), question: "What is the chemical symbol for oxygen?",
        subject: "Chemistry",
        topic: "Elements",
        difficulty: "Easy",
        marks: 6,
    },







];





module.exports = { data: sampleListings };
